minimal_mistakes_skin : "dark"

# Site Settings
locale  : "euc-KR"
title : "leekwy Blog"
title_separator : "-"
subtitle  :
name  : "딥러닝"
description : "딥러닝 관련 블로그입니다"

# Site Author
author:
  name  : "leekwy"
  avatar  :
  bio : "leekwy's Blog"
  location  : "Seoul KOREA"
  email :
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
    - label: "Website"
      icon: "fa fa-fw fa-link"
